// <auto-generated />
namespace NLIH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewAddition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewAddition));
        
        string IMigrationMetadata.Id
        {
            get { return "202112111626155_NewAddition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
